# Тестовые задания. Каримов Ильдар

## Задание № 1 (Numpy):

1. Создать двумерный массив из случайных чисел от 0 до 1 размером 10х10 и вывести на экран.
2. Найти индекс (номер строки и номер столбца) максимального элемента.
3. Переставить столбцы так, чтобы в первой строке массива значения шли по возрастанию.
4. Отнормировать значения в каждой строке (то есть для каждой строки найти сумму элементов
и разделить на эту сумму каждый элемент строки).
5. Заменить значения массива, которые больше 0.5, на -1.
6. Вывести полученный массив на экран.

## Решение:

### 1. Создать двумерный массив из случайных чисел от 0 до 1 размером 10х10 и вывести на экран.

In [1]:
# Импортируем необходимые библиотеки

import pandas as pd
import numpy as np
import random

In [2]:
rand_arr = np.random.rand(10, 10) # cоздаем двумерный массив из случайных чисел 
rand_arr # выведем на экран массив

array([[0.04233612, 0.70867944, 0.10415282, 0.15358427, 0.24378466,
        0.74741651, 0.65970975, 0.94612363, 0.43110383, 0.87224384],
       [0.64480468, 0.88411368, 0.89209467, 0.77952586, 0.86346515,
        0.80270493, 0.05913538, 0.15156052, 0.02396925, 0.75320417],
       [0.46677821, 0.73146443, 0.16991395, 0.54714527, 0.9075424 ,
        0.32174489, 0.49493472, 0.89706413, 0.68833546, 0.01455527],
       [0.58090355, 0.0748311 , 0.12228389, 0.46312617, 0.6548099 ,
        0.24753392, 0.08317446, 0.91617693, 0.42566571, 0.92521981],
       [0.10546451, 0.22945269, 0.58195711, 0.36031742, 0.62781047,
        0.5664763 , 0.57932852, 0.6675845 , 0.14692021, 0.35361266],
       [0.63725604, 0.85466407, 0.43357312, 0.54353496, 0.88921471,
        0.96006484, 0.32621693, 0.8979235 , 0.90678788, 0.74404112],
       [0.94257867, 0.66398745, 0.10174752, 0.38728711, 0.51354741,
        0.34604147, 0.86745097, 0.0947798 , 0.04336814, 0.2770424 ],
       [0.63841749, 0.0152056 , 0.06448439, 0.15831663, 0.03568743,
        0.93295148, 0.27446676, 0.86226864, 0.4171811 , 0.03248736],
       [0.31164955, 0.05843141, 0.80977275, 0.85018205, 0.07710953,
        0.67541544, 0.47451783, 0.47265327, 0.58070315, 0.90943339],
       [0.45883609, 0.37844329, 0.00191495, 0.99611234, 0.19984403,
        0.95350006, 0.39903783, 0.35817189, 0.16151208, 0.41171806]])

### 2. Найти индекс (номер строки и номер столбца) максимального элемента.

In [3]:
max_row, max_col = np.unravel_index(rand_arr.argmax(), rand_arr.shape) # найдем индекс маскимального элемента 
print("Максимальный элемент находится в строке", max_row, "и в столбце", max_col) # выведем на экран строки и столбца

Максимальный элемент находится в строке 9 и в столбце 3

### 3. Переставить столбцы так, чтобы в первой строке массива значения шли по возрастанию.

In [4]:
rand_arr = rand_arr[::, rand_arr[0,].argsort()[::1]] # отсортируем массив с помощью функции argsort()

In [5]:
rand_arr # проверим сортировку

array([[0.04233612, 0.10415282, 0.15358427, 0.24378466, 0.43110383,
        0.65970975, 0.70867944, 0.74741651, 0.87224384, 0.94612363],
       [0.64480468, 0.89209467, 0.77952586, 0.86346515, 0.02396925,
        0.05913538, 0.88411368, 0.80270493, 0.75320417, 0.15156052],
       [0.46677821, 0.16991395, 0.54714527, 0.9075424 , 0.68833546,
        0.49493472, 0.73146443, 0.32174489, 0.01455527, 0.89706413],
       [0.58090355, 0.12228389, 0.46312617, 0.6548099 , 0.42566571,
        0.08317446, 0.0748311 , 0.24753392, 0.92521981, 0.91617693],
       [0.10546451, 0.58195711, 0.36031742, 0.62781047, 0.14692021,
        0.57932852, 0.22945269, 0.5664763 , 0.35361266, 0.6675845 ],
       [0.63725604, 0.43357312, 0.54353496, 0.88921471, 0.90678788,
        0.32621693, 0.85466407, 0.96006484, 0.74404112, 0.8979235 ],
       [0.94257867, 0.10174752, 0.38728711, 0.51354741, 0.04336814,
        0.86745097, 0.66398745, 0.34604147, 0.2770424 , 0.0947798 ],
       [0.63841749, 0.06448439, 0.15831663, 0.03568743, 0.4171811 ,
        0.27446676, 0.0152056 , 0.93295148, 0.03248736, 0.86226864],
       [0.31164955, 0.80977275, 0.85018205, 0.07710953, 0.58070315,
        0.47451783, 0.05843141, 0.67541544, 0.90943339, 0.47265327],
       [0.45883609, 0.00191495, 0.99611234, 0.19984403, 0.16151208,
        0.39903783, 0.37844329, 0.95350006, 0.41171806, 0.35817189]])

### 4. Отнормировать значения в каждой строке (то есть для каждой строки найти сумму элементов и разделить на эту сумму каждый элемент строки).

In [6]:
rand_arr_normalized = rand_arr/rand_arr.sum(axis=1) # делим каждый элемент на сумму элементов

In [7]:
rand_arr_normalized # выведем отнормированный массив на экран

array([[0.00862395, 0.01778998, 0.02931289, 0.05425001, 0.10218335,
        0.09171199, 0.16722693, 0.21781254, 0.16710073, 0.21905621],
       [0.13134793, 0.15237556, 0.14877928, 0.19214907, 0.00568137,
        0.00822092, 0.2086241 , 0.23392472, 0.14429563, 0.03509084],
       [0.0950836 , 0.02902241, 0.10442742, 0.20195769, 0.16315425,
        0.06880518, 0.1726035 , 0.09376308, 0.00278844, 0.20769745],
       [0.11833115, 0.02088688, 0.08839165, 0.14571649, 0.10089437,
        0.01156281, 0.01765788, 0.07213647, 0.17724964, 0.21212265],
       [0.02148332, 0.09940205, 0.06876971, 0.13970824, 0.03482409,
        0.0805375 , 0.0541439 , 0.16508284, 0.0677436 , 0.15456599],
       [0.12981025, 0.07405711, 0.10373837, 0.19787918, 0.21493343,
        0.04535025, 0.20167489, 0.27978263, 0.14254021, 0.20789642],
       [0.19200505, 0.01737914, 0.07391711, 0.11428099, 0.01027943,
        0.1205919 , 0.15668097, 0.1008436 , 0.05307459, 0.02194439],
       [0.13004684, 0.01101435, 0.0302161 , 0.00794161, 0.09888328,
        0.03815601, 0.00358806, 0.27188124, 0.00622379, 0.19964125],
       [0.0634836 , 0.13831444, 0.16226463, 0.01715938, 0.13764246,
        0.06596685, 0.01378805, 0.19682995, 0.17422535, 0.10943352],
       [0.09346577, 0.00032709, 0.19011669, 0.04447179, 0.03828276,
        0.05547372, 0.08930118, 0.27786952, 0.07887518, 0.08292762]])

### 5. Заменить значения массива, которые больше 0.5, на -1.

Для наглядности заменим значения в исходном массиве, т.к. в отнормированном массиве все значения меньше 0,5.

In [8]:
rand_arr[rand_arr>0.5] = -1 # заменим значения массива, которые больше 0.5, на -1

### 6. Вывести полученный массив на экран.

In [9]:
rand_arr # выведем массив на экран

array([[ 0.04233612,  0.10415282,  0.15358427,  0.24378466,  0.43110383,
        -1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        ,  0.02396925,
         0.05913538, -1.        , -1.        , -1.        ,  0.15156052],
       [ 0.46677821,  0.16991395, -1.        , -1.        , -1.        ,
         0.49493472, -1.        ,  0.32174489,  0.01455527, -1.        ],
       [-1.        ,  0.12228389,  0.46312617, -1.        ,  0.42566571,
         0.08317446,  0.0748311 ,  0.24753392, -1.        , -1.        ],
       [ 0.10546451, -1.        ,  0.36031742, -1.        ,  0.14692021,
        -1.        ,  0.22945269, -1.        ,  0.35361266, -1.        ],
       [-1.        ,  0.43357312, -1.        , -1.        , -1.        ,
         0.32621693, -1.        , -1.        , -1.        , -1.        ],
       [-1.        ,  0.10174752,  0.38728711, -1.        ,  0.04336814,
        -1.        , -1.        ,  0.34604147,  0.2770424 ,  0.0947798 ],
       [-1.        ,  0.06448439,  0.15831663,  0.03568743,  0.4171811 ,
         0.27446676,  0.0152056 , -1.        ,  0.03248736, -1.        ],
       [ 0.31164955, -1.        , -1.        ,  0.07710953, -1.        ,
         0.47451783,  0.05843141, -1.        , -1.        ,  0.47265327],
       [ 0.45883609,  0.00191495, -1.        ,  0.19984403,  0.16151208,
         0.39903783,  0.37844329, -1.        ,  0.41171806,  0.35817189]])

In [10]:
df = pd.DataFrame(rand_arr) # преобразуем в датафрейм
df # выведем таблицу

,0,1,2,3,4,5,6,7,8,9
0,0.042336,0.104153,0.153584,0.243785,0.431104,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
1,-1.000000,-1.000000,-1.000000,-1.000000,0.023969,0.059135,-1.000000,-1.000000,-1.000000,0.151561
2,0.466778,0.169914,-1.000000,-1.000000,-1.000000,0.494935,-1.000000,0.321745,0.014555,-1.000000
3,-1.000000,0.122284,0.463126,-1.000000,0.425666,0.083174,0.074831,0.247534,-1.000000,-1.000000
4,0.105465,-1.000000,0.360317,-1.000000,0.146920,-1.000000,0.229453,-1.000000,0.353613,-1.000000
5,-1.000000,0.433573,-1.000000,-1.000000,-1.000000,0.326217,-1.000000,-1.000000,-1.000000,-1.000000
6,-1.000000,0.101748,0.387287,-1.000000,0.043368,-1.000000,-1.000000,0.346041,0.277042,0.094780
7,-1.000000,0.064484,0.158317,0.035687,0.417181,0.274467,0.015206,-1.000000,0.032487,-1.000000
8,0.311650,-1.000000,-1.000000,0.077110,-1.000000,0.474518,0.058431,-1.000000,-1.000000,0.472653
9,0.458836,0.001915,-1.000000,0.199844,0.161512,0.399038,0.378443,-1.000000,0.411718,0.358172